apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vus5bt9l3-python 
  janus-idp.io/tekton: vus5bt9l3-python
  backstage.io/kubernetes-id: vus5bt9l3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vus5bt9l3-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml